### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by sivakov512** [syohex/emacs-libyaml#1]
Please, help, how to install this library?

Maybe you can provide a little guide?

**Comment by dmitry-saritasa** [comment]
I also stuck on this one

**Comment by pkulev** [comment]
## What you need for compilation
* Installed Emacs (>=25), configured with `--with-modules` flag
* Emacs sources (for emacs-module.h)
* Installed libyaml headers (libyaml-devel for redhat-based distros)

## Compilation
* `EMACS_ROOT=/path/to/emacs/sources make`
* copy `libyaml-core.so` and `libyaml.el` somewhere, `libyaml.el` must be in load-path

## Runtime
* libyaml library must be installed
* run emacs: `emacs -L /path/to/directory/with/so` or add path in config `(add-to-list 'load-path "/path/to/directory/with/so")`

`(require 'libyaml)` must work.
