### ISSUE TITLE
Put this on Melpa?

### ISSUE THREAD

**Issue by wyuenho** [syohex/emacs-libyaml#4]
It would be nice if this could be installed from Melpa so more people will use it and contribute.

**Comment by syohex** [comment]
I'm afraid that I no longer use Emacs and it is difficult for me to maintain this. And there is already YAML parser(https://github.com/zkry/yaml.el) in MELPA, please check it.

**Comment by wyuenho** [comment]
That one is completely based on lisp and it's so incredible slow.

If you could grant me permission to this repo I can fix it up to a state where it will build the module with github actions, and then I'll put it on Melpa.

**Comment by syohex** [comment]
I have invited you as collaborator.

**Comment by wyuenho** [comment]
Thanks, I think I'll need higher access as I won't be able to configure github actions as a collaborator.

**Comment by syohex** [comment]
You'll send PR of github actions, I'll merge it.

**Comment by wyuenho** [comment]
Sorry I've found a much easier way to [parse yaml](https://daseldocs.tomwright.me/) quickly without libyaml, I no longer wish or have the need to work on this project. Thank you for granting me the permissions, you can remove my privilege now.
